'use client'

import React from 'react';
import Image from 'next/image';
import { SAMPLE_IMAGES } from './constants';
import { useRouter } from 'next/navigation';

export const Homepage = () => {
  const router = useRouter();
  return (
    <div className='relative flex flex-col justify-center h-[100vh] items-center'>
           <div className='flex flex-col'>
        <p className='relative justify-center margin-auto text-white text-[32px] md:text-[46px] font-thin font-[Open Sans] text-center'>AI Art Gallery</p>
        <p className='relative justify-center margin-auto text-white text-[14px] font-thin font-[Open Sans] text-center'>A collection of art generated by Midjourney and DALL•E</p>
      </div>
      <div className='grid grid-cols-8 gap-2 mt-8'>
          {SAMPLE_IMAGES.map((image, index) => (
              <div className='relative group cursor-pointer' key={index} onClick={() => router.push('/gallery')}>
                <div className='absolute top-0 left-0 bg-[rgba(0,0,0,0.6)] z-2 w-full h-full hidden md:flex group-hover:hidden'></div>
                <Image
                  key={index}
                  width={64}
                  height={64}
                  className={`rounded-lg w-full h-full object-cover`}
                  src={image}
                  alt={`Image ${index + 1}`}
                />
              </div>
            ))}
      </div>
      <p className="shimmer mt-8 text-[20px] text-white"><a href='/gallery'>Enter Gallery</a></p>
    </div>
  )
}
