import './globals.css'

export const metadata = {
  title: 'AI Art Gallery',
  description: 'A collection of art generated by Midjourney and DALL•E',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black pb-8 h-[100vh]'>{children}</body>
    </html>
  )
}
